apiVersion: v1
kind: Service
metadata:
  name: backend
spec:
  selector: 
    app: second-app
  ports:
    - protocol: 'TCP'
      port: 80
      targetPort: 80
  type: LoadBalancer
---
apiVersion: apps/v1
kind: Deployment
metadata:
  name: narchitecture-deployment
spec:
  replicas: 1
  selector:
    matchLabels:
      app: narchitecture
      tier: backend
  template:
    metadata: 
      labels:
        app: narchitecture
        tier: backend
    spec: 
      containers:
        - name: narchitecture-node
          image: melihvarilci/melihvarilci-webapi-image:1.0
          imagePullPolicy: Always
          livenessProbe: 
            httpGet:
              path: /
              port: 80
            periodSeconds: 10
            initialDelaySeconds: 5
