apiVersion: v1
kind: Service
metadata:
  name: backend
  labels:
    group: example
spec:
  selector: 
    app: narchitecture
  ports:
    - protocol: 'TCP'
      port: 80
      targetPort: 80
    # - protocol: 'TCP'
    #   port: 443
    #   targetPort: 443
  type: LoadBalancer